# SPDX-License-Identifier: GPL-2.0+
#
# Makefile
#
# Copyright (C) 2023 Variscite Ltd - http://www.variscite.com/

ifeq ($(CONFIG_SKIP_LOWLEVEL_INIT),)
obj-$(CONFIG_TARGET_AM335X_VAR_SOM)		:= mux.o
endif

obj-$(CONFIG_TARGET_AM335X_VAR_SOM)		+= board.o
